// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg0_GdqeYfTVS2BEqF2IheVRNFoJSQ0lg',
    appId: '1:132538518546:web:5d5033d439637782d61ccb',
    messagingSenderId: '132538518546',
    projectId: 'live-score-app-9fd98',
    authDomain: 'live-score-app-9fd98.firebaseapp.com',
    storageBucket: 'live-score-app-9fd98.firebasestorage.app',
    measurementId: 'G-Z2N8M6JRCP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqOvOJGsbs5zLY9VtM5lT-Ek-JKNMvsmE',
    appId: '1:132538518546:android:5ec7c57d4eb57ad0d61ccb',
    messagingSenderId: '132538518546',
    projectId: 'live-score-app-9fd98',
    storageBucket: 'live-score-app-9fd98.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK12zm8QpR7OWVuXlznPss_XflAojs5pk',
    appId: '1:132538518546:ios:d3ceb96302a175e7d61ccb',
    messagingSenderId: '132538518546',
    projectId: 'live-score-app-9fd98',
    storageBucket: 'live-score-app-9fd98.firebasestorage.app',
    iosBundleId: 'com.example.liveScoreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCK12zm8QpR7OWVuXlznPss_XflAojs5pk',
    appId: '1:132538518546:ios:d3ceb96302a175e7d61ccb',
    messagingSenderId: '132538518546',
    projectId: 'live-score-app-9fd98',
    storageBucket: 'live-score-app-9fd98.firebasestorage.app',
    iosBundleId: 'com.example.liveScoreApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg0_GdqeYfTVS2BEqF2IheVRNFoJSQ0lg',
    appId: '1:132538518546:web:af809b0464a86ef5d61ccb',
    messagingSenderId: '132538518546',
    projectId: 'live-score-app-9fd98',
    authDomain: 'live-score-app-9fd98.firebaseapp.com',
    storageBucket: 'live-score-app-9fd98.firebasestorage.app',
    measurementId: 'G-QLMHSC3FFV',
  );
}
